# Generated by Django 2.0.6 on 2018-07-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expId', models.IntegerField(default=-1)),
                ('expName', models.CharField(max_length=200)),
                ('kinddatdesc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExpL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('madrigalUrl', models.CharField(default=' ', max_length=200)),
                ('name', models.CharField(default=' ', max_length=400)),
                ('realUrl', models.CharField(default=' ', max_length=200)),
                ('url', models.CharField(default=' ', max_length=200)),
                ('madid', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='expf',
            name='epxl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfls.ExpL'),
        ),
    ]
