# Generated by Django 2.0.6 on 2018-07-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expf',
            old_name='epxl',
            new_name='expl',
        ),
    ]
