# Generated by Django 2.0.7 on 2018-08-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfls', '0002_auto_20180716_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesDwnld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(max_length=200, upload_to='media/')),
            ],
        ),
    ]
