# Generated by Django 2.0.6 on 2018-07-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('access', models.CharField(default=' ', max_length=200)),
                ('endday', models.IntegerField(default=0)),
                ('endhour', models.IntegerField(default=0)),
                ('endmin', models.IntegerField(default=0)),
                ('endmonth', models.IntegerField(default=0)),
                ('endsec', models.IntegerField(default=0)),
                ('endyear', models.IntegerField(default=0)),
                ('madid', models.IntegerField(default=0)),
                ('instcode', models.IntegerField(default=0)),
                ('instname', models.CharField(default=' ', max_length=200)),
                ('madrigalUrl', models.CharField(default=' ', max_length=200)),
                ('name', models.CharField(default=' ', max_length=400)),
                ('pi', models.CharField(default=' ', max_length=200)),
                ('piEmail', models.CharField(default=' ', max_length=200)),
                ('realUrl', models.CharField(default=' ', max_length=200)),
                ('siteid', models.IntegerField(default=0)),
                ('sitename', models.CharField(default=' ', max_length=200)),
                ('startdate', models.IntegerField(default=0)),
                ('starthour', models.IntegerField(default=0)),
                ('startmin', models.IntegerField(default=0)),
                ('startmonth', models.IntegerField(default=0)),
                ('startsec', models.IntegerField(default=0)),
                ('startyear', models.IntegerField(default=0)),
                ('url', models.CharField(default=' ', max_length=200)),
                ('version', models.CharField(default=' ', max_length=200)),
            ],
        ),
    ]
