# Generated by Django 2.0.6 on 2018-07-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='access',
        ),
        migrations.RemoveField(
            model_name='question',
            name='endday',
        ),
        migrations.RemoveField(
            model_name='question',
            name='endhour',
        ),
        migrations.RemoveField(
            model_name='question',
            name='endmin',
        ),
        migrations.RemoveField(
            model_name='question',
            name='endmonth',
        ),
        migrations.RemoveField(
            model_name='question',
            name='endsec',
        ),
        migrations.RemoveField(
            model_name='question',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='question',
            name='instcode',
        ),
        migrations.RemoveField(
            model_name='question',
            name='instname',
        ),
        migrations.RemoveField(
            model_name='question',
            name='madid',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pi',
        ),
        migrations.RemoveField(
            model_name='question',
            name='piEmail',
        ),
        migrations.RemoveField(
            model_name='question',
            name='siteid',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sitename',
        ),
        migrations.RemoveField(
            model_name='question',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='question',
            name='starthour',
        ),
        migrations.RemoveField(
            model_name='question',
            name='startmin',
        ),
        migrations.RemoveField(
            model_name='question',
            name='startmonth',
        ),
        migrations.RemoveField(
            model_name='question',
            name='startsec',
        ),
        migrations.RemoveField(
            model_name='question',
            name='startyear',
        ),
        migrations.RemoveField(
            model_name='question',
            name='version',
        ),
    ]
