# Generated by Django 2.0.6 on 2018-07-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_urls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Urls',
        ),
    ]
