# Generated by Django 2.0.6 on 2018-07-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180712_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='madid',
            field=models.IntegerField(default=-1),
        ),
    ]
