# Generated by Django 2.0.6 on 2018-07-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_question_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpListFileNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expId', models.IntegerField(default=-1)),
                ('expName', models.CharField(max_length=200)),
                ('kinddatdesc', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
